apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ng-sample
  name: sample-service
  namespace: sample
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: ng-sample
status:
  loadBalancer: {}
