apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: sample-ingress
  namespace: sample
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: sample-service
              servicePort: 8080